stages:
    - build
    - test
    - quality-gate

cache:
    key: "pid_${CI_PROJECT_ID}_cache"
    paths:
        - node_modules/
        - dist/
        - coverage/

build-job:
    stage: build
    script:
        - rm -rf dist/* || true
        - npm install
        - npm run build

test-job:
    stage: test
    script:
        - rm -rf coverage/* || true
        - npm test

quality-gate-job:
    stage: quality-gate
    script:
        - sonar-scanner
