stages:
    - build
    - test
    - quality-gate

cache:
    paths:
        - node_modules
        - dist

build-project:
    stage: build
    script:
        - npm install
        - npm run build

test-project:
    stage: test
    script: npm test

quality:
    stage: quality-gate
    script:
        - sonar-scanner