stages:
    - build
    - test

cache:
    paths:
        - node_modules
        - dist

build-project:
    stage: build
    script:
        - npm install
        - npm run build

test-project:
    stage: test
    script: npm test